from .dataset import EXAMPLE_PAYLOAD_SPARKPLUGB_DATASET
from .json import EXAMPLE_PAYLOAD_SPARKPLUGB_JSON
from .timeseries import EXAMPLE_PAYLOAD_SPARKPLUGB_TIMESERIES


example_payloads = {
    "dataset": EXAMPLE_PAYLOAD_SPARKPLUGB_DATASET,
    "json": EXAMPLE_PAYLOAD_SPARKPLUGB_JSON,
    "timeseries": EXAMPLE_PAYLOAD_SPARKPLUGB_TIMESERIES,
}
